script:
  - docker run -v `pwd`:/book tomkwong/jupyter-book-tools /bin/bash -c 'cd /book; /bin/bash build.sh'
  
after_success:
  - echo "successful"
 
deploy:
  provider: pages
  local-dir: build
  target-branch: gh-pages
  verbose: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
